vpc-name      = "Tetris-vpc"
igw-name      = "Tetris-igw"
subnet-name   = "Tetris-subnet"
rt-name       = "Tetris-route-table"
sg-name       = "Tetris-sg"
instance-name = "Tetris-server"
key-name      = "Tetris"
iam-role      = "Tetris-iam-role"
